In [1]:
import matplotlib.pyplot as plt 
import numpy as np
from mpl_toolkits.mplot3d import axes3d

import matplotlib
import time
from matplotlib.widgets import Slider, Button


In [3]:
matplotlib.use('tkAgg')



In [4]:
# %matplotlib widget
# %matplotlib inline


In [5]:
# #kOORD:       [  X   ,  Y  ,  Z  ]
# H1E=np.array([ 480.0, 6.33,-8.38]) 
# H1W=np.array([ 480.0,-6.64,-8.38]) 
# H2W=np.array([ 360.0,-6.64,-6.64]) 
# H3E=np.array([ 240.0, 6.33,-4.45])
# H3W=np.array([ 240.0,-6.64,-4.45]) 
# H4E=np.array([ 120.0, 6.33,-2.48]) 
# H4W=np.array([ 120.0,-6.64,-2.48]) 
# H5E=np.array([-7.0  , 6.33, -0.4]) 
# H5W=np.array([-7.0  ,-6.64, -0.4]) 
# H6E=np.array([-120.0, 6.33,-2.25]) 
# H6W=np.array([-120.0,-6.64,-2.25]) 
# H7E=np.array([-240.0, 6.33,-4.22]) 
# H7W=np.array([-240.0,-6.64,-4.22]) 
# H8E=np.array([-360.0, 6.33,-6.18]) 
# H9E=np.array([-480.0, 6.33,-8.15]) 
# H9W=np.array([-480.0,-6.64,-8.15])
# H2E_int= (H1E+H3E)/2
# H8W_int = (H7W+H9W)/2

# DOFs=np.array([H1E,H1W,H2E_int,H2W,H3E,H3W,H4E,H4W,H5E,H5W,H6E,H6W,H7E,H7W,H8E,H8W_int,H9E,H9W])
# DOFs=np.flip(DOFs,axis=0)

# # print(DOFs)
# def connectivity(DOFs,index):
#     x_out=[]
#     y_out=[]
#     z_out=[]        
#     for i in index:
#         for j,DOF in enumerate(DOFs):
#             x=[]
#             y=[]
#             z=[]            
#             x.append(DOFs[j,0])   # start points for each line
#             y.append(DOFs[j,1])   
#             z.append(DOFs[j,2]) 
            
#             if i+j>len(DOFs)-1:
#                 x.append(DOFs[j,0])   
#                 y.append(DOFs[j,1])   
#                 z.append(DOFs[j,2])   
#                 continue
#             if j//2 != j/2:

#                 if i==2: 
#                     x.append(DOFs[j+i,0])   
#                     y.append(DOFs[j+i,1])   
#                     z.append(DOFs[j+i,2])  
#                 else:
#                     x.append(DOFs[j,0])   
#                     y.append(DOFs[j,1])   
#                     z.append(DOFs[j,2]) 

#             else:
#                 x.append(DOFs[j+i,0])   
#                 y.append(DOFs[j+i,1])   
#                 z.append(DOFs[j+i,2])   
#             x_out.append(x)   
#             y_out.append(y)   
#             z_out.append(z)   
#     return np.array(x_out),np.array(y_out),np.array(z_out)

# x,y,z=connectivity(DOFs,[1,2])

# data=[]
# for i in range(len(x)):

#     data.append(x[i])
#     data.append(y[i])
#     # data.append(z[i])
# print(DOFs[1])

In [6]:
def deformed(phi,fac):
    '''Adding i deformation vector to the original coordinates of the sensors
    Arrguments: 
        phi: 1darray
            length 48
            [x1,y1,z1,x2....]
        fac: float
            Factor for scaling the deformations 
    returns: 
        DOFs: 1darray
            length 54 (!!!) 
            H2E and H8W are interpolated linearly from the neighbouring points.
    '''
    #kOORD:       [  X   ,  Y  ,  Z  ]
    H1E=np.array([ 480.0, 6.33,-8.38]) 
    H1W=np.array([ 480.0,-6.64,-8.38])
    H2W=np.array([ 360.0,-6.64,-6.64]) 
    H3E=np.array([ 240.0, 6.33,-4.45])
    H3W=np.array([ 240.0,-6.64,-4.45]) 
    H4E=np.array([ 120.0, 6.33,-2.48]) 
    H4W=np.array([ 120.0,-6.64,-2.48]) 
    H5E=np.array([-7.0  , 6.33, -0.4]) 
    H5W=np.array([-7.0  ,-6.64, -0.4]) 
    H6E=np.array([-120.0, 6.33,-2.25]) 
    H6W=np.array([-120.0,-6.64,-2.25]) 
    H7E=np.array([-240.0, 6.33,-4.22]) 
    H7W=np.array([-240.0,-6.64,-4.22]) 
    H8E=np.array([-360.0, 6.33,-6.18]) 
    H9E=np.array([-480.0, 6.33,-8.15]) 
    H9W=np.array([-480.0,-6.64,-8.15])

    DOFs_sensors=np.array([H1E,H1W,H2W,H3E,H3W,H4E,H4W,H5E,H5W,H6E,H6W,H7E,H7W,H8E,H9E,H9W])
    # for i in range(len(DOFs_sensors)):
    #     DOFs_sensors[i,0]+=phi[3*i]*fac
    #     DOFs_sensors[i,1]+=phi[3*i+1]*fac
    #     DOFs_sensors[i,2]+=phi[3*i+2]*fac
    DOFs_sensors[:,0]+=phi[0::3]*fac
    DOFs_sensors[:,1]+=phi[1::3]*fac
    DOFs_sensors[:,2]+=phi[2::3]*fac

    H2E_int= (DOFs_sensors[0]+DOFs_sensors[3])/2
    H8W_int = (DOFs_sensors[12]+DOFs_sensors[15])/2

    DOFs=np.insert(DOFs_sensors,2,H2E_int,axis=0)
    DOFs=np.insert(DOFs,15,H8W_int,axis=0)
    DOFs=np.flip(DOFs,axis=0)
    return DOFs




In [7]:
def create_phi(x,y,z):
    '''Create a phi vector based on x, y, z - vectors'''
    phi=[]
    for i in range(len(x)): 
        phi.append(x[i])
        phi.append(y[i])
        phi.append(z[i])
    return np.array(phi)


t=np.linspace(0,6,16)
z=np.sin(t)

phi=create_phi(z*0,z*0,z)
# print(phi)
DOFs=deformed(phi,100)

In [8]:
i=range(0,len(DOFs)-1,1)

def plottt(DOFs,ax,i):
    ax.scatter3D(DOFs[:,0],DOFs[:,1],DOFs[:,2])
    
    lines=[]
    for j in i:
        if j<len(DOFs)-2:
            lines.append(plot(ax,DOFs,j,j+2))
        if j%2 ==0:
           lines.append(plot(ax,DOFs,j,j+1)) 
    return lines
def plot(ax,DOFs,i,j):
    return ax.plot3D([DOFs[i,0],DOFs[j,0]],[DOFs[i,1],DOFs[j,1]],[DOFs[i,2],DOFs[j,2]],color='black')



In [9]:
def show_mode_3d(phi):
    matplotlib.use('tkAgg')
    

    fig = plt.figure(figsize=(10,6))
    ax=fig.add_subplot(111,projection='3d')
    ax.set_box_aspect((1, 0.05, 0.01))
    # ax.set_aspect(1.5)
    # def update()
    # ax.scatter3D(DOFs[:,0],DOFs[:,1],DOFs[:,2])
    ax.set_axis_off()
    i=range(0,len(DOFs)-1,1)
    ax.set_zlim(-20,10)


    axfreq = fig.add_axes([0.05, 0.05, 0.03, 0.6])
    fac_slider = Slider(
    ax=axfreq,
    label='Amplification\n factor',
    valmin=0,
    valmax=110,
    valinit=10,
    orientation="vertical"
    )

    axfreq = fig.add_axes([0.1, 0.05, 0.03, 0.6])
    t_slider = Slider(
    ax=axfreq,
    label='Phase',
    valmin=-1,
    valmax=1,
    valinit=1,
    orientation="vertical"
    )

    def update(val): 
        ax.clear()
        DOFs=deformed(phi,fac_slider.val*t_slider.val*10)
        ax.set_zlim(-20,10)
        ax.set_axis_off()
        linjer=plottt(DOFs,ax,i)
        fig.canvas.draw_idle()
    update(100)


    fac_slider.on_changed(update)
    t_slider.on_changed(update)
    plt.show()




show_mode_3d(phi)

In [10]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.set_title('Wireframe Plot')

#getting test data
X, Y, Z = axes3d.get_test_data(0.05)
x=np.array([[1,2,3,4,5],[1,2,3,4,5]])
y=np.array([[1,1,1,1,1],[3,3,3,3,3]])
z=np.array([[1,1,1,1,5],[1,1,1,1,5]])
print(X)
#drawing wireframe plot
cb = ax.plot_wireframe(x, y, z, cstride=1,
                          rstride=1, color="green")

plt.show()

[[-30.  -29.5 -29.  ...  28.5  29.   29.5]
 [-30.  -29.5 -29.  ...  28.5  29.   29.5]
 [-30.  -29.5 -29.  ...  28.5  29.   29.5]
 ...
 [-30.  -29.5 -29.  ...  28.5  29.   29.5]
 [-30.  -29.5 -29.  ...  28.5  29.   29.5]
 [-30.  -29.5 -29.  ...  28.5  29.   29.5]]


In [5]:
matplotlib.use('tkagg')
class mode_plot():
    def __init__(self,DOFs_sensors,phi):
        self.DOFs_sensors=DOFs_sensors

        H2E_int= (DOFs_sensors[0]+DOFs_sensors[3])/2
        H8W_int = (DOFs_sensors[12]+DOFs_sensors[15])/2

        base_H10E=np.array([655  ,  7, 1]) 
        base_H10W=np.array([655  , -7.3, 1]) 
        base_H11E=np.array([-655 ,  7, 1]) 
        base_H11W=np.array([-655,  -7.3, 1]) 

        dummy_H10E =np.array([655  ,  7, 1])  
        dummy_H10W=np.array([655  , -7.3, 1]) 
        dummy_H11E=np.array([-655 ,  7, 1]) 
        dummy_H11W=np.array([-655,  -7.3, 1]) 
        # dummy2= 

        self.DOFs=np.insert(DOFs_sensors,2,H2E_int,axis=0)
        self.DOFs=np.insert(self.DOFs,15,H8W_int,axis=0)

        self.x0=self.DOFs[:,0]
        self.y0=self.DOFs[:,1]
        self.z0=self.DOFs[:,2]
        self.phi=phi
        self.fig = plt.figure(figsize=(10,10))
        self.ax=self.fig.add_subplot(111,projection='3d')

        self.ax.set_box_aspect((1, 0.05, 0.01))
        self.ax.set_axis_off()
        plt.subplots_adjust(left=0, bottom=0,
        right=1, top=1, wspace=0, hspace=0)

        # plotting initial 
        self.dots = self.ax.plot(self.x0,self.y0,self.z0,marker='.',
                    linestyle='None')[0]

        X=np.array([self.x0[::2],self.x0[1::2]])
        Y=np.array([self.y0[::2],self.y0[1::2]])
        Z=np.array([self.z0[::2],self.z0[1::2]])

        self.lines=self.ax.plot_wireframe(X,Y,Z,
        rstride=1,cstride=1,color='black',linewidth=1)

        ints=np.array([H2E_int,H8W_int])
        self.dots_int=self.ax.plot(ints[:,0],ints[:,1],ints[:,2],
        marker='.',linestyle='None',color='red')[0]

        #plotting undeformed
        self.dots_perm = self.ax.plot(self.x0,self.y0,self.z0,
        marker='.',linestyle='None',color='grey',alpha=0.2)[0]

        X=np.array([self.x0[::2],self.x0[1::2]])
        Y=np.array([self.y0[::2],self.y0[1::2]])
        Z=np.array([self.z0[::2],self.z0[1::2]])
        self.lines_perm=self.ax.plot_wireframe(X,Y,Z,
        rstride=1,cstride=1,color='grey',alpha=0.2)
  
        #setting up the sliders
        self.ax.set_zlim(-20,10)
        axfreq = self.fig.add_axes([0.05, 0.05, 0.03, 0.6])
        self.fac_slider = Slider(
        ax=axfreq,
        label='Amplification\n factor',
        valmin=0,
        valmax=110,
        valinit=10,
        orientation="vertical")

        axfreq = self.fig.add_axes([0.1, 0.05, 0.03, 0.6])
        self.t_slider = Slider(
        ax=axfreq,
        label='Phase',
        valmin=-1,
        valmax=1,
        valinit=1,
        orientation="vertical")

        self.fac_slider.on_changed(self.update_DOFs)
        self.t_slider.on_changed(self.update_DOFs)

    def update_DOFs(self,event):
 
        fac=self.fac_slider.val*self.t_slider.val
        DOFs_i=np.zeros_like(self.DOFs_sensors[:])
        DOFs_i[:,0]=self.DOFs_sensors[:,0]+self.phi[0::3]*fac
        DOFs_i[:,1]=self.DOFs_sensors[:,1]+self.phi[1::3]*fac
        DOFs_i[:,2]=self.DOFs_sensors[:,2]+self.phi[2::3]*fac

        H2E_int= (DOFs_i[0]+DOFs_i[3])/2
        H8W_int = (DOFs_i[12]+DOFs_i[15])/2

        ints=np.array([H2E_int,H8W_int])

        DOFs_i=np.insert(DOFs_i,2,H2E_int,axis=0)
        DOFs_i=np.insert(DOFs_i,15,H8W_int,axis=0)

        # updating the sensor DOFs
        self.dots.set_xdata(DOFs_i[:,0].ravel())
        self.dots.set_ydata(DOFs_i[:,1].ravel())
        self.dots.set_3d_properties(DOFs_i[:,2].ravel())

        #Updating marking of interpolated DOFs
        self.dots_int.set_xdata(ints[:,0].ravel())
        self.dots_int.set_ydata(ints[:,1].ravel())
        self.dots_int.set_3d_properties(ints[:,2].ravel())

        #updating wireframe
        X=np.array([DOFs_i[0::2,0],DOFs_i[1::2,0]])
        Y=np.array([DOFs_i[0::2,1],DOFs_i[1::2,1]])
        Z=np.array([DOFs_i[0::2,2],DOFs_i[1::2,2]])
        #drawing new wireframe
        self.lines.remove()
        self.lines=self.ax.plot_wireframe(X, Y, Z, cstride=1,
                          rstride=1, color="black")
        print(self.ax.get_box_aspect())
        self.fig.canvas.draw()
        
    def show(self):
        mng = plt.get_current_fig_manager()
        mng.window.state('zoomed') #works fine on Windows!
        plt.show()   
        

In [6]:
H1E=np.array([ 480.0, 6.33,-8.38]) 
H1W=np.array([ 480.0,-6.64,-8.38])
H2W=np.array([ 360.0,-6.64,-6.64]) 
H3E=np.array([ 240.0, 6.33,-4.45])
H3W=np.array([ 240.0,-6.64,-4.45]) 
H4E=np.array([ 120.0, 6.33,-2.48]) 
H4W=np.array([ 120.0,-6.64,-2.48]) 
H5E=np.array([-7.0  , 6.33, -0.4]) 
H5W=np.array([-7.0  ,-6.64, -0.4]) 
H6E=np.array([-120.0, 6.33,-2.25]) 
H6W=np.array([-120.0,-6.64,-2.25]) 
H7E=np.array([-240.0, 6.33,-4.22]) 
H7W=np.array([-240.0,-6.64,-4.22]) 
H8E=np.array([-360.0, 6.33,-6.18]) 
H9E=np.array([-480.0, 6.33,-8.15]) 
H9W=np.array([-480.0,-6.64,-8.15])

H10E=np.array([655  ,  4.5, 120.5]) 
H10W=np.array([655  , -4.5, 120.5]) 
H11E=np.array([-655 ,  4.5, 120.5]) 
H11W=np.array([-655,  -4.5, 120.5]) 

DOFs_sensors=np.array([H1E,H1W,H2W,H3E,H3W,H4E,H4W,H5E,H5W,H6E,H6W,H7E,H7W,H8E,H9E,H9W,H10E,H10W,H11E,H11W])

def create_phi(x,y,z):
    '''Create a phi vector based on x, y, z - vectors'''
    phi=[]
    for i in range(len(x)): 
        phi.append(x[i])
        phi.append(y[i])
        phi.append(z[i])
    return np.array(phi)


t=np.linspace(0,20,20)
z=np.sin(t)

phi=create_phi(z*0,z*0,z)

test=mode_plot(DOFs_sensors,phi)
test.show()

[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]
[1.8270904  0.09135452 0.0182709 ]


In [13]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Button

class DummyPlot(object):
    def __init__(self):
        self.imsize = (10, 10)
        self.data = np.random.random(self.imsize)

        self.fig, self.ax = plt.subplots()
        self.im = self.ax.imshow(self.data)

        buttonax = self.fig.add_axes([0.45, 0.9, 0.1, 0.075])
        self.button = Button(buttonax, 'Update')
        self.button.on_clicked(self.update)

    def update(self, event):
        self.data += np.random.random(self.imsize) - 0.5
        self.im.set_data(self.data)
        self.im.set_clim([self.data.min(), self.data.max()])
        self.fig.canvas.draw()

    def show(self):
        plt.show()

p = DummyPlot()
p.show()

In [14]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider, Button


# The parametrized function to be plotted
def f(t, amplitude, frequency):
    return amplitude * np.sin(2 * np.pi * frequency * t)

t = np.linspace(0, 1, 1000)

# Define initial parameters
init_amplitude = 5
init_frequency = 3

# Create the figure and the line that we will manipulate
fig, ax = plt.subplots()
line, = ax.plot(t, f(t, init_amplitude, init_frequency), lw=2)
ax.set_xlabel('Time [s]')

# adjust the main plot to make room for the sliders
fig.subplots_adjust(left=0.25, bottom=0.25)

# Make a horizontal slider to control the frequency.
axfreq = fig.add_axes([0.25, 0.1, 0.65, 0.03])
freq_slider = Slider(
    ax=axfreq,
    label='Frequency [Hz]',
    valmin=0.1,
    valmax=30,
    valinit=init_frequency,
)

# Make a vertically oriented slider to control the amplitude
axamp = fig.add_axes([0.1, 0.25, 0.0225, 0.63])
amp_slider = Slider(
    ax=axamp,
    label="Amplitude",
    valmin=0,
    valmax=10,
    valinit=init_amplitude,
    orientation="vertical"
)


# The function to be called anytime a slider's value changes
def update(val):
    line.set_ydata(f(t, amp_slider.val, freq_slider.val))
    fig.canvas.draw_idle()


# register the update function with each slider
freq_slider.on_changed(update)
amp_slider.on_changed(update)

# Create a `matplotlib.widgets.Button` to reset the sliders to initial values.
resetax = fig.add_axes([0.8, 0.025, 0.1, 0.04])
button = Button(resetax, 'Reset', hovercolor='0.975')


def reset(event):
    freq_slider.reset()
    amp_slider.reset()
button.on_clicked(reset)

plt.show()

In [15]:
arr=np.array([1,2,3,4])
print(arr[1::2])

[2 4]
