In [2]:
import sys
import os
src_path='../../src'
if not src_path in sys.path:
    sys.path.insert(1,src_path)

from preposessing import *

%load_ext autoreload
%autoreload 2

In [9]:
pre_fucked='HB141M-2015-09-15_01-25-16.mat'
fucked='HB141M-2015-10-23_02-56-55.mat'
ok='HB141M-2015-10-28_08-33-15.mat'
post_ok='HB141M-2015-11-06_22-26-12.mat'

In [10]:
pf_file=import_file('D:/ProcessedData_Hardanger_mat/',pre_fucked)
f_file=import_file('D:/ProcessedData_Hardanger_mat/',fucked)
ok_file=import_file('D:/ProcessedData_Hardanger_mat/',ok)
pok_file=import_file('D:/ProcessedData_Hardanger_mat/',post_ok)


In [36]:
def get_axis(obj):
    
    recording=obj.data.get('recording')
    # print(recording)
    sensors=recording.get('sensor')
    coordinate_system=recording.get('general').get('coordinate_system')
    # print(coordinate_system)
    for sensor in sensors:
        inspect_sensor(sensor)
    # print((sensor[0]))

def get_transformation_matrices(obj): 
    recording=obj.data.get('recording')
    sensors=recording.get('sensor')
    transes=np.array([])
    for sensor in sensors:
        
        inspect_sensor(sensor)

def compare_trans_matrices(obj1,obj2):
    rec1=obj1.data.get('recording')
    rec2=obj2.data.get('recording')

    sens1=rec1.get('sensor')
    sens2=rec2.get('sensor')
    equal=True
    for s1,s2 in zip(sens1,sens2):
        
        n1=s1.get('sensor_name')
        n2=s2.get('sensor_name')
        print('Comaring ',n1,' and ',n2)
        

        trans1=s1.get('transformation_matrix')
        trans2=s2.get('transformation_matrix')
        if n1[0]=='A':
            if np.all(trans1==trans2):
                print('   OK  ')
                for i,row in enumerate(trans1):
                    print('    '+f'{str(trans1[i]):<30}',trans2[i])

            else: 
                for i,row in enumerate(trans1):
                    print('    '+f'{str(trans1[i]):<30}',trans2[i])

                equal=False  
            continue
        or1=s1.get('orientation').split('-')
        or2=s2.get('orientation').split('-')
        if np.all(trans1==trans2):
            print('   OK  ')
            for i,row in enumerate(trans1):
                print('    '+f'{str(trans1[i]):<30}',trans2[i])
            print('    Labeled orientation: ')
            print('    '+f'{or1[0]:<30}',or2[0])
            print('   '+f'{or1[1]:<30}',or2[1])
        else: 
            for i,row in enumerate(trans1):
                print('    '+f'{str(trans1[i]):<30}',trans2[i])
            print('    Labeled orientation: ')
            print('    '+f'{or1[0]:<30}',or2[0])
            print('   '+f'{or1[1]:<30}',or2[1])
            equal=False    
        print('\n\n')
    return equal

def inspect_sensor(sensor):
    print(sensor.get('sensor_name'))
    # component=sensor.get('component')
    # print('     ,',component.get('data_quality'))
    # print('     ,',sensor.get('orientation'))
    print('     ',sensor.get('transformation_matrix'))
    print('\n\n')

# Negative X upwards - Positive Z longitudinal
compare_trans_matrices(f_file,ok_file)
# get_axis(f_file)
# print('######################################################')
# get_axis(ok_file)

Comaring  H1 East  and  H1 East
   OK  
    [-1.  0.  0.]                  [-1.  0.  0.]
    [ 0. -1.  0.]                  [ 0. -1.  0.]
    [0. 0. 1.]                     [0. 0. 1.]
    Labeled orientation: 
    Negative X upwards             Negative X upwards 
    Positive Z longitudinal        Positive Z longitudinal



Comaring  H1 Vest  and  H1 Vest
   OK  
    [-1.  0.  0.]                  [-1.  0.  0.]
    [ 0. -1.  0.]                  [ 0. -1.  0.]
    [0. 0. 1.]                     [0. 0. 1.]
    Labeled orientation: 
    Negative X upwards             Negative X upwards 
    Positive Z longitudinal        Positive Z longitudinal



Comaring  H2 Vest  and  H2 Vest
   OK  
    [-1.  0.  0.]                  [-1.  0.  0.]
    [ 0. -1.  0.]                  [ 0. -1.  0.]
    [0. 0. 1.]                     [0. 0. 1.]
    Labeled orientation: 
    Negative X upwards             Negative X upwards 
    Positive Z longitudinal        Positive Z longitudinal



Comaring  H3 East  

False

In [36]:
get_axis(f_file)
print('\n\n\n')
get_axis(ok_file)

{'general': {'comments': 'Data from Hardanger Bridge full scale experiment', 'coordinate_system': 'global', 'datalogger': 'HB141M', 'datenumber': array(10689.12286175), 'duration': array(1859.99), 'geographic_location': 'Hordaland, Norway', 'latitude': '57°13\'38.64" N', 'longitude': '018°09\'03.63" E', 'origin': 'midspan of the bridge, on deck', 'postlen': array(1800.), 'prelen': array(60.), 'recording': 'HB141M-2015-10-23_02-56-55', 'references': None, 'samplerate': array(200.), 'sensor_setup': {'report': array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29.]), 'valid_from': '06/12/2014', 'valid_to': '24/10/2015'}, 'starttime': '23/10/2015 02:56:55.255', 'structure_name': 'Hardanger Bridge', 'structure_type': 'Suspension Bridge', 'title': 'CUSP M data file', 'trigcode': array(1.), 'x_axis': 'longitudinal, along the bridge (from Vallavik to Bu)', 'y_axis': 'transverse to the 

In [16]:
print(f_file.data.keys())


dict_keys(['recording'])


In [14]:
f_ts=f_file.convert()

In [ ]:
print(f_ts.)